INSERT INTO dishes (id, category, name, description, img_url, ingredients, price, created_at, updated_at)
VALUES
    (NULL, 'soup', 'Minestrone', 'Klasszikus olasz zöldségleves', './images/menu/soup_minestrone.png', '["10", "23", "45"]', 5.99, NULL, NULL),
    (NULL, 'soup', 'Zuppa Toscana', 'Toszkán kolbászos és kelkáposztás leves', './images/menu/soup_toscana.png', '["15", "32", "78"]', 6.99, NULL, NULL),
    (NULL, 'soup', 'Zuppa di pomodoro', 'Klasszikus olasz paradicsomleves', './images/menu/soup_tomato.png', '["21", "39", "47"]', 5.49, NULL, NULL),
    (NULL, 'salad', 'Caprese', 'Friss paradicsom és mozzarella', './images/menu/salad_caprese.png', '["8", "12", "35"]', 7.99, NULL, NULL),
    (NULL, 'salad', 'Caesar', 'Romaine saláta és krutonok', './images/menu/salad_caesare.png', '["14", "27", "49"]', 8.49, NULL, NULL),
    (NULL, 'salad', 'Arugula', 'Rukkola, cseresznye paradicsom', './images/menu/salad_pesto_shrimp.png', '["18", "36", "44"]', 6.99, NULL, NULL),
    (NULL, 'pizza', 'Margherita', 'Pizza tészta, paradicsom szósz, mozzarella, bazsalikom', './images/menu/pizza_margherita.png', '["17", "7", "8", "13"]', 10.99, NULL, NULL),
    (NULL, 'pizza', 'Pepperoni', 'Paradicsom szósz, mozzarella, pepperoni', './images/menu/pizza_salame.png', '["17", "7", "8", "9", "31"]', 11.99, NULL, NULL),
    (NULL, 'pizza', 'Quattro Stagioni', 'Pizza tészta, paradicsom szósz, mozzarella, articsóka, sonka, gomba', './images/menu/pizza_mushroom.png', '["17", "7", "8", "11", "19", "28"]', 12.49, NULL, NULL),
    (NULL, 'pasta', 'Spaghetti Bolognese', 'Hagyományos húsos szósz', './images/menu/pasta_bolognese.png', '["20", "29", "37"]', 9.99, NULL, NULL),
    (NULL, 'pasta', 'Fettuccine Alfredo', 'Krémes parmezán szósz', './images/menu/pasta_carbonare.png', '["16", "24", "42"]', 11.49, NULL, NULL),
    (NULL, 'pasta', 'Arrabiata', 'Klasszikus pardicsomos, csípős tészta', './images/menu/pasta_arrabiata.png', '["22", "30", "48"]', 12.99, NULL, NULL),
    (NULL, 'dessert', 'Tiramisu', 'Kávé ízesítésű olasz desszert', './images/menu/dessert_tiramisu.png', '["25", "38", "50"]', 6.99, NULL, NULL),
    (NULL, 'dessert', 'Cannoli', 'Sült tészta tészta, édes krém', './images/menu/dessert_cannoli.png', '["33", "40", "46"]', 5.49, NULL, NULL),
    (NULL, 'dessert', 'Panna Cotta', 'Édesített tejszín, vanília', './images/menu/dessert_panna_cotta.png', '["34", "41", "43"]', 4.99, NULL, NULL),
    (NULL, 'drinks', 'Espresso', 'Erős fekete kávé', './images/menu/drink_espresso.png', '["1", "3", "5"]', 2.49, NULL, NULL),
    (NULL, 'drinks', 'Thé Verde', 'Zöldtea ízesítésű jegestea', './images/menu/drink_sanbenedetto_green.png', '["2", "4", "6"]', 7.99, NULL, NULL),
    (NULL, 'drinks', 'Acqua Panna', 'Szénsavmentes természetes ásványvíz', './images/menu/drink_acqua_panna.png', '["45", "47", "50"]', 9.99, NULL, NULL);
