INSERT INTO ingredients (id, name, allergen, in_stock, created_at, updated_at)
VALUES
(1, 'Coffee', NULL, 1, NULL, NULL),
(2, 'Lemon', NULL, 1, NULL, NULL),
(3, 'Water', NULL, 1, NULL, NULL),
(4, 'Sugar', NULL, 1, NULL, NULL),
(5, 'Espresso', NULL, 1, NULL, NULL),
(6, 'Alcohol', NULL, 1, NULL, NULL),
(7, 'Tomato', NULL, 1, NULL, NULL),
(8, 'Mozzarella', 'Dairy', 1, NULL, NULL),
(9, 'Pepperoni', 'Pork', 1, NULL, NULL),
(10, 'Vegetable Broth', NULL, 1, NULL, NULL),
(11, 'Artichokes', NULL, 1, NULL, NULL),
(12, 'Lettuce', NULL, 1, NULL, NULL),
(13, 'Basil', NULL, 1, NULL, NULL),
(14, 'Parmesan', 'Dairy', 1, NULL, NULL),
(15, 'Pasta', 'Gluten', 1, NULL, NULL),
(16, 'Cream', 'Dairy', 1, NULL, NULL),
(17, 'Flour', 'Gluten', 1, NULL, NULL),
(18, 'Cherry Tomatoes', NULL, 1, NULL, NULL),
(19, 'Ham', 'Pork', 1, NULL, NULL),
(20, 'Ground Beef', 'Beef', 1, NULL, NULL),
(21, 'Cannellini Beans', NULL, 1, NULL, NULL),
(22, 'Lasagna Sheets', 'Gluten', 1, NULL, NULL),
(23, 'Carrots', NULL, 1, NULL, NULL),
(24, 'Fettuccine', 'Gluten', 1, NULL, NULL),
(25, 'Cocoa Powder', NULL, 1, NULL, NULL),
(26, 'Croutons', 'Gluten', 1, NULL, NULL),
(27, 'Mushrooms', NULL, 1, NULL, NULL),
(28, 'Spaghetti', 'Gluten', 1, NULL, NULL),
(29, 'Ricotta Cheese', 'Dairy', 1, NULL, NULL),
(30, 'Prosciutto', 'Pork', 1, NULL, NULL),
(31, 'Sausage', 'Pork', 1, NULL, NULL),
(32, 'Pastry Dough', 'Gluten', 1, NULL, NULL),
(33, 'Mascarpone', 'Dairy', 1, NULL, NULL),
(34, 'Rosemary', NULL, 1, NULL, NULL),
(35, 'Ricotta', 'Dairy', 1, NULL, NULL),
(36, 'Vanilla', NULL, 1, NULL, NULL),
(37, 'Parmesan', 'Dairy', 1, NULL, NULL),
(38, 'Gelatin', NULL, 1, NULL, NULL),
(39, 'Anchovies', 'Fish', 1, NULL, NULL),
(40, 'Olives', NULL, 1, NULL, NULL),
(41, 'Arugula', NULL, 1, NULL, NULL),
(42, 'Heavy Cream', 'Dairy', 1, NULL, NULL),
(43, 'White Wine', 'Alcohol', 1, NULL, NULL),
(44, 'Red Wine', 'Alcohol', 1, NULL, NULL),
(45, 'Ground Beef', 'Beef', 1, NULL, NULL),
(46, 'Eggs', 'Eggs', 1, NULL, NULL),
(47, 'Cherry Tomatoes', NULL, 1, NULL, NULL),
(48, 'Chocolate', 'Dairy', 1, NULL, NULL),
(49, 'Sour Cream', 'Dairy', 1, NULL, NULL),
(50, 'Honey', NULL, 1, NULL, NULL);
