INSERT INTO ingredients (id, name, allergen, in_stock, created_at, updated_at)
VALUES
(1, 'Kávé', NULL, 1, NULL, NULL),
(2, 'Citrom', NULL, 1, NULL, NULL),
(3, 'Víz', NULL, 1, NULL, NULL),
(4, 'Cukor', NULL, 1, NULL, NULL),
(5, 'Espresso', NULL, 1, NULL, NULL),
(6, 'Alkohol', NULL, 1, NULL, NULL),
(7, 'Paradicsom', NULL, 1, NULL, NULL),
(8, 'Mozzarella', 'Tejtermék', 1, NULL, NULL),
(9, 'Pepperoni', 'Sertés', 1, NULL, NULL),
(10, 'Zöldségleves', NULL, 1, NULL, NULL),
(11, 'Articsóka', NULL, 1, NULL, NULL),
(12, 'Saláta', NULL, 1, NULL, NULL),
(13, 'Bazsalikom', NULL, 1, NULL, NULL),
(14, 'Parmezán', 'Tejtermék', 1, NULL, NULL),
(15, 'Tészta', 'Glutén', 1, NULL, NULL), 
(16, 'Tejszín', 'Tejtermék', 1, NULL, NULL),
(17, 'Liszt', 'Glutén', 1, NULL, NULL),
(18, 'Cseresznye paradicsom', NULL, 1, NULL, NULL),
(19, 'Sonka', 'Sertés', 1, NULL, NULL),
(20, 'Darált marhahús', 'Marha', 1, NULL, NULL),
(21, 'Cannellini bab', NULL, 1, NULL, NULL),
(22, 'Lasagna lapok', 'Glutén', 1, NULL, NULL),
(23, 'Répa', NULL, 1, NULL, NULL),
(24, 'Fettuccine', 'Glutén', 1, NULL, NULL),
(25, 'Kakaópor', NULL, 1, NULL, NULL),
(26, 'Kenyérkockák', 'Glutén', 1, NULL, NULL),
(27, 'Gomba', NULL, 1, NULL, NULL),
(28, 'Spagetti', 'Glutén', 1, NULL, NULL),
(29, 'Ricotta sajt', 'Tejtermék', 1, NULL, NULL),
(30, 'Prosciutto', 'Sertés', 1, NULL, NULL),
(31, 'Kolbász', 'Sertés', 1, NULL, NULL),
(32, 'Tészta tészta', 'Glutén', 1, NULL, NULL),
(33, 'Mascarpone', 'Tejtermék', 1, NULL, NULL),
(34, 'Rozmaring', NULL, 1, NULL, NULL),
(35, 'Ricotta', 'Tejtermék', 1, NULL, NULL),
(36, 'Vanília', NULL, 1, NULL, NULL),
(37, 'Parmezán', 'Tejtermék', 1, NULL, NULL),
(38, 'Zselatin', NULL, 1, NULL, NULL),
(39, 'Anchovies', 'Hal', 1, NULL, NULL),
(40, 'Olajbogyó', NULL, 1, NULL, NULL),
(41, 'Rukkola', NULL, 1, NULL, NULL),
(42, 'Tejszínhab', 'Tejtermék', 1, NULL, NULL),
(43, 'Fehérbor', 'Alkohol', 1, NULL, NULL),
(44, 'Vörösbor', 'Alkohol', 1, NULL, NULL),
(45, 'Darált marhahús', 'Marha', 1, NULL, NULL),
(46, 'Tojás', 'Tojás', 1, NULL, NULL),
(47, 'Cseresznye paradicsom', NULL, 1, NULL, NULL),
(48, 'Csokoládé', 'Tejtermék', 1, NULL, NULL),
(49, 'Tejföl', 'Tejtermék', 1, NULL, NULL),
(50, 'Méz', NULL, 1, NULL, NULL);
