// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RestaurantDesktopApp;
//
//    var ingredients = Ingredients.FromJson(jsonString);

namespace RestaurantDesktopApp
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Ingredients
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("allergen")]
        public string Allergen { get; set; }

        [JsonProperty("in_stock")]
        public long InStock { get; set; }
    }

    public partial class Ingredients
    {
        public static Ingredients[] FromJson(string json) => JsonConvert.DeserializeObject<Ingredients[]>(json, RestaurantDesktopApp.ConverterIngerdients.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Ingredients[] self) => JsonConvert.SerializeObject(self, RestaurantDesktopApp.ConverterIngerdients.Settings);
    }

    internal static class ConverterIngerdients
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
