// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RestaurantDesktopApp;
//
//    var user = User.FromJson(jsonString);

namespace RestaurantDesktopApp
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class User
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("first_name")]
        public string FirstName { get; set; }

        [JsonProperty("last_name")]
        public string LastName { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("zip")]
        public long Zip { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }
    }

    public partial class User
    {
        public static User[] FromJson(string json) => JsonConvert.DeserializeObject<User[]>(json, RestaurantDesktopApp.ConverterUser.Settings);
    }
    
    /*
    public static class Serialize
    {
        public static string ToJson(this User[] self) => JsonConvert.SerializeObject(self, RestaurantDesktopApp.ConverterUser.Settings);
    }
    */

    internal static class ConverterUser
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
